apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: wordpress
      protocol: layer2
      addresses:
      - 172.17.0.20-172.17.0.20
    - name: ftps
      protocol: layer2
      addresses:
      - 172.17.0.21-172.17.0.21
    - name: default
      protocol: layer2
      addresses:
      - 172.17.0.10-172.17.0.19