apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: test
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: ftps
    port: 21
    targetPort: 21
    protocol: TCP
  - name: data
    port: 30000
    targetPort: 30000
    protocol: TCP