apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
  annotations:
    metallb.universe.tf/allow-shared-ip: test
spec:
  type: ClusterIP
  selector:
    app: influxdb
  ports:
  - name: http
    port: 8086
    targetPort: 8086
    protocol: TCP

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  labels:
    app: influxdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G