apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  type: ClusterIP
  selector:
    app: influxdb
  ports:
  - port: 8086
    targetPort: 8086
    protocol: TCP
    name: http

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-volume
  labels:
    app: influxdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G