apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: test
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - name: http
    port: 5050
    targetPort: 5050
    protocol: TCP