apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - image: service_influxdb
        name: influxdb
        imagePullPolicy: Never
        livenessProbe:
          tcpSocket:
            port: 8086
        ports:
          - containerPort: 8086
            name: influxdb
        volumeMounts:
        - name: influxdb-pv
          mountPath: /var/lib/influxdb
      volumes:
      - name: influxdb-pv
        persistentVolumeClaim:
          claimName: influxdb-pvc