apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: service_mysql
        name: mysql
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
          name: mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-volume